name: gotest
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  gotest:
    strategy:
      matrix:
        module: ["dayone", "daytwo", "daythree", "dayfour", "dayfive"]
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: go test
        run: go test ./${{matrix.module}}/...
